language: python
python:
 - '2.7'
 - '3.4'
 - '3.5'
 - '3.6'
install:
 - pip install git+https://github.com/ejhigson/nestcheck # for more up to date version than on PyPI
 - pip install .
 - pip install coveralls
script:
 - nosetests --with-coverage --cover-erase --cover-package=dyPolyChord
after_success:
 - coveralls
